### ISSUE TITLE
limit string length of forum post content preview

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#1]
in fourm.ejs `<%= msg.body.substring(0,100) %>` was throwing an error. 

`<%= msg.body //.substring(0,100) %>` fixed the issue, but created a new problem altogether. The entire message body now displays where only a preview should be.

**Comment by holaymolay** [comment]
This error would occur when `msg.body` came back as `undefined`.

fixed with a simple conditional.

**Comment by zsediqyar** [comment]
I don't know if they are related, but there is now another issue with the New form.
http://www.codeclub.social/forum/new

**Comment by holaymolay** [comment]
This was my error. I committed changes improperly on dev. It's fixed now. I would have encountered this soon anyway.
