### ISSUE TITLE
Replace Forum table with <div>

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#11]
It's always better to use div's for the page layout & structure.

**Comment by zsediqyar** [comment]
You can assign this to me and I will sort it out.

**Comment by holaymolay** [comment]
While this issue has been addressed, I feel that it has brought up another issue entirely. The current appearance of the forum better represents a blog or latest new page.

Closing issue and opening a new feature enhancement.
