### ISSUE TITLE
FEATURE: Direct Messaging

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#15]
An internal mail system enabling users to send private messages directly to each other.

**Comment by craig429** [comment]
RocketChat seems to already have this feature. Are you looking for a different style of messaging?

**Comment by holaymolay** [comment]
yes I would like a separate messaging system for the website itself aside from rocketchat. it has the added benefit of sending notifications, mail within the website Etc. this is something we can also discuss tomorrow at the meeting

**Comment by holaymolay** [comment]
After talking about this at last night's meetup, we've decided to put this on hold. Further discussion is required to determine whether this is truly a necessary feature. The same thing could be accomplished with email notifications.

**Comment by holaymolay** [comment]
found a library to help facilitate p2p chat, file sharing, and Audio / Video
https://github.com/peers/peerjs-server

**Comment by holaymolay** [comment]
closing  for now. we can always reopen at a later date.
