### ISSUE TITLE
express-session deprecation

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#29]
receiving the following message at startup:
```
express-session deprecated undefined resave option; provide resave option app.js:46:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:46:9
```

The code this is referring to is:
`app.use(session({ secret: 'keyboard cat', cookie: { maxAge: 60000 }}));`

**Comment by craig429** [comment]
Oops, thought I closed this when I fixed it a while back. `session` params have been updated, this is history.
