### ISSUE TITLE
mongodb deprecation warning for Db.prototype.authenticate

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#30]
`Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.`

**Comment by craig429** [comment]
Ooops, didn't see this in time. See narrative in Issue #31. Assigning myself.

**Comment by holaymolay** [comment]
why'd you close this?

**Comment by holaymolay** [comment]
I'm reopening because I don't see a clear reason for closure in the comments.

**Comment by craig429** [comment]
Sorry. "Close" should be it's OWN BUTTON!

**Comment by holaymolay** [comment]
lol. I hear it is only a problem among the "unemployed"

**Comment by craig429** [comment]
This warning will go away when we merge validation_branch. Closing.
