### ISSUE TITLE
Email Verification for new users

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#34]
- A quick search led me to this module (not saying we must use it): https://github.com/whitef0x0/node-email-verification
- Here's a discussion on stackoverflow: https://stackoverflow.com/questions/39092822/how-to-do-confirm-email-address-with-express-node

**Comment by craig429** [comment]
Okay, signup form triggers a verify e-mail if:
1. Fields are not blank
2. Email is correctly formatted
3. Password is at least 5 characters with at least 1 numeral
The verify page waits for an acknowledge, which comes when the user clicks the link in the e-mail. The user document has a Boolean called `verified`. If the user tries to log in without `verified == true` the login fails. When the verification arrives `verified` is set to `true` in the user document and the page is redirected to login, with a verification acknowledgement.
Closing this.
