### ISSUE TITLE
session does not persist after leaving site

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#37]
user session does not persist when, after logging in, someone leaves the site and then returns. We should allow user to remain authenticated for a period of time (24 hrs?) before being logged out.

**Comment by craig429** [comment]
A direct consequence of my having to implement the `resave` option to eliminate the deprecated warnings, no doubt. Assigning myself.

**Comment by holaymolay** [comment]
Another example of this is when I was working on the forum page. When I made some chances to the view and tried to refresh the page it would forget that I was logged in and,  thus, the forum link went missing. Each time, I had to re-log in... over and over and over again. This needs to be a priority because it is becoming a hindrance.

**Comment by craig429** [comment]
Session cookie timeout was one minute, which has been extended to a day. We can also make it infinite, but I dunno how good an idea that is.
Using the "close and comment" button in the correct manner this time. This issue is history.
