### ISSUE TITLE
bodyParser.urlencoded({extended:... has both true and false values

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#38]
in [app.js](https://github.com/codeclubsocial/codeclub_website_dev/blame/dev/app.js#L44)

app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.urlencoded({ extended: false }));

I think false needs to remain, but I'm not 100% sure.

**Comment by craig429** [comment]
Here is a concise Stackoverflow answer to the question about the difference:
[https://stackoverflow.com/questions/29136374/what-the-difference-between-qs-and-querystring](url)
Here is the Github API description:
[https://github.com/expressjs/body-parser](url)

I don't see any downside to using `extended: true` so I'm sticking with that and closing this issue.

**Comment by craig429** [comment]
I really wish I understood why these links don't work from inside this page but work fine if you copy and paste them into the browser.

**Comment by holaymolay** [comment]
try using markdown syntax
