### ISSUE TITLE
cookie determines whether someone has account

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#39]
Server should issue a cookie that allows the server to determine whether the visitor has previously logged in with a user account. 

If yes, `'/'` loads  index
If no, `'/'` loads landing page

**Comment by craig429** [comment]
We made session cookies infinite on last night's commit:
[https://github.com/codeclubsocial/codeclub_website_dev/commit/8a54b501fd207bcc60165897fd020e543e4ddc55](url)
We can redirect based on the result of `req.isAuthenticated()`. I will go ahead and do that. But keep in mind that if we decide at some future date to make session cookies expire we will need an alternate mechanism to establish "previously visited" status.

**Comment by craig429** [comment]
[https://github.com/codeclubsocial/codeclub_website_dev/commit/8a54b501fd207bcc60165897fd020e543e4ddc55](url)

**Comment by craig429** [comment]
Wow, that link didn't work! If I cut and paste it into my browser it works good. Hmmm........

**Comment by craig429** [comment]
https://github.com/codeclubsocial/codeclub_website_dev/commit/cd3c3955ec2e78069125a197b7dffe83b699213d

**Comment by craig429** [comment]
Git automatically inserted the above comment, presumably based on my reference to the issue number in the commit narrative. Pretty sweet. And THEIR link works just fine.
Closing this issue.
