### ISSUE TITLE
add details about git merge --no-ff my_feature_branch on contribute page

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#44]
$ `git merge --no-ff my_feature_branch`

the `--no-ff` will preserve the network graph on github

instead of merging all the commits onto one line it is recommended that you only use --no-ff when you're merging into dev... it really wont matter when you're merging dev into your feature branch in order to update the feature branch.

This needs to be added to the Contribution page on the site.

**Comment by craig429** [comment]
Done. Closing this.
