### ISSUE TITLE
disable authentication for development work

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#58]

**Comment by craig429** [comment]
OK, I dunno if this is such a good idea, but here goes.
There is now a variable in `app.js` called `enableAuth`. It is located near the top of the file near variable localDB (line 41 for this commit).
If you set `enableAuth` to false it will bypass the passport authentication mechanism and show you logged in when you access the site. Be sure to set this to `true` for production.
Closing this.
