### ISSUE TITLE
FEATURE: User Authentication & User Accounts

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#7]
By implementing User Authentication & User Accounts numerous other features will be possible.

**Comment by craig429** [comment]
Created login_branch. I don't know why the graph isn't available from the branches page like git_sandbox, but it is here:
https://github.com/codeclubsocial/codeclub_website_dev/network

**Comment by craig429** [comment]
Oops, I think I closed this issue by mistake on my last comment, so this is a reopen comment.

**Comment by holaymolay** [comment]
Found a great article on how to do this https://medium.com/of-all-things-tech-progress/starting-with-authentication-a-tutorial-with-node-js-and-mongodb-25d524ca0359

**Comment by holaymolay** [comment]
Craig made significant progress on this issue. He implemented passport and user signups. Now we have to build out the site to take advantage of the new functionality.

**Comment by craig429** [comment]
Some fixes I need to make and test Twitter, Facebook, and Google login. Brian also mentioned a Git login, so I'll see if I can get that going, then I should be ready to close this.
Also need to get back on login_branch. I did not mean to merge my stuff in to dev, I just wanted to pull. So I need to spend some time in the git sandbox this weekend to clarify my understanding on pulls, pushes, merges, patches, and stashes. I would claim I never merged my code, but the Git network graph tells a different story.
And Brian please sequester the live site so newbies like me don't end up taking it down with inadvertent merges and pushes. I intend to develop on login_branch and pull periodically from dev to keep myself up to date, but sometimes this doesn't happen.

**Comment by holaymolay** [comment]
Craig, when updating your feature branch you must do this...

**First, Update Dev:**
$ `git checkout dev`
$ `git pull origin dev` _// This updates dev to current_

**Then Update login_branch from Dev:**
$ `git checkout login_branch`
$ `git merge dev` _// This merges dev into login_branch and updates login_branch_

**Finally (when ready), Merge your features back into Dev:**
$ `git checkout dev `
$ `git merge login_branch` _// This merges login_branch back into dev_

**Comment by holaymolay** [comment]
Thanks to Craig I am updating this issue to Incomplete Feature. _That's a good thing!_

**Comment by craig429** [comment]
Your instructions worked great. I am now back on login_branch with all the latest and greatest from dev. Changed localDB to false and pushed and it didn't break anything!

**Comment by holaymolay** [comment]
perfect!

**Comment by craig429** [comment]
OK, sign-in/login/logout appears to work in local mode. Header reflects the state of login/logout and brute force attempt to get to a protected page (i.e. http://www.codeclub.social/secret) gets kicked back if user is not logged in.
I need to get Google, Facebook and Twitter OAuth working and we can close this.
localDB is set to "true", so flip it before merging into dev.

**Comment by holaymolay** [comment]
Good work Craig!

I'd also like to have certain pages only available when logged in. 

When **not** logged in there should only be:
1.  Landing Page
2. Index
3. About
4. Contact
5. Login / Sign Up
6. Links
7. Blog
8. Latest News

everything else should be protected behind authentication:

- chat
- forum
- user profiles
- wiki / knowledgebase
etc.

**Comment by craig429** [comment]
OK, this looks like the real deal. Chat and Forum are not visible in the page header unless you are logged in. Brute force attempts to access pages are kicked back. I explored Google/Twitter/Facebook login strategies but they all seem to require developer tweaks on the G/T/FB side, so I'm declaring them out of scope and closing this issue (not by accident this time).

I would like to schedule a code review with any interested parties before we merge login_branch into dev. This should be short and pro forma but it would be good to get procedures in place for when we have numerous contributors. Having explicit buy-in from the rest of the group for a functional change such as this is important in my humble opinion.

**Comment by holaymolay** [comment]
I agree let's discuss this in detail tomorrow at the meet up. Thanks for all your hard work on this feature.

**Comment by holaymolay** [comment]
**Just to add few more discussion topics:**
- Perhaps we should get the message boards fully functional so these things can be discussed in detail.
- I propose Rich Text Editors should all be in the Markdown format. It's a well-accepted format and is perfect for what we need it for. Plus much quicker to implement.
