### ISSUE TITLE
ISSUE: Page Footer

### ISSUE THREAD

**Issue by zsediqyar** [codeclubsocial/codeclub_website_dev#8]
The footer doesn't seem to be fixed at the bottom of the page and it jumps around with certain style implications.

**Comment by holaymolay** [comment]
I've noticed that. I tried to fix it last week, but it created problems for some pages. Once the content is filled in on an affected page it will no longer be a problem. 

I would like to find a permanent solution to this, except the only solution I have tried broke the landing page. So I had to reverse the changes.

Unless you have any objections, I say we close this for now and come back to this if it continues to be a problem once the site is completed.

Please let me know your thoughts...

**Comment by holaymolay** [comment]
I am going to close this issue for now. We can reopen it if this becomes an ongoing problem. I don't think there's anything we can do about it right now.
