### ISSUE TITLE
Field validation

### ISSUE THREAD

**Issue by holaymolay** [codeclubsocial/codeclub_website_dev#9]
need to implement [express-validation](https://github.com/ctavan/express-validator) & [express-sanitizer](https://www.npmjs.com/package/express-sanitizer)

**Comment by craig429** [comment]
Just assigned to myself. I guess I enjoy implementing traffic-cop types of features.

**Comment by holaymolay** [comment]
here is another library i came across, it was recommended by someone... It looks powerful and easy to implement.

[https://github.com/cure53/DOMPurify](https://github.com/cure53/DOMPurify)

**Comment by craig429** [comment]
###  Three failures will prevent signup:
- email field is not a properly formatted email address
- password field does not contain at least 6 characters and one digit
- email address is already in the database.



###  One failure will prevent login:
- email and password don't exist or don't match.

### Relevant messages are flashed in red in the signup/login form. They need formatting.
